/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DAO.DAOEmpleadoImpl;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class PqrsAdmin extends javax.swing.JFrame {

    private String id_Adm;
    private DAOEmpleadoImpl emp = new DAOEmpleadoImpl();
    
    
    /**
     * Creates new form PqrsAdmin
     */
    public PqrsAdmin() {
        initComponents();
        
        ArrayList<String> pendientes = new ArrayList();
        try {
            pendientes = emp.pqrsPendientes();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        Iterator iter = pendientes.iterator();
            while (iter.hasNext()) {
                String tmp = iter.next().toString();
                this.cbPqrs.addItem(tmp);
            }

    }
    
    public void setId(String id){
        
        id_Adm = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameMedidas = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbPqrsRespondidas = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        taMedidaATomar = new javax.swing.JTextArea();
        btRegMedida = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        frameMedidas2 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbPqrsRespondidas2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taMedidaTomada = new javax.swing.JTextArea();
        btFinalizarMedida = new javax.swing.JButton();
        cbMedidas = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbPqrs = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRespuesta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btResponder = new javax.swing.JButton();
        btMedidasRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btMedidasConsultar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setText("Medidas PQRS");

        taMedidaATomar.setColumns(20);
        taMedidaATomar.setRows(5);
        jScrollPane2.setViewportView(taMedidaATomar);

        btRegMedida.setText("Registrar");
        btRegMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegMedidaActionPerformed(evt);
            }
        });

        jLabel5.setText("Ticket");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cbPqrsRespondidas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                        .addGap(156, 156, 156))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegMedida)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPqrsRespondidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRegMedida)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameMedidasLayout = new javax.swing.GroupLayout(frameMedidas.getContentPane());
        frameMedidas.getContentPane().setLayout(frameMedidasLayout);
        frameMedidasLayout.setHorizontalGroup(
            frameMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        frameMedidasLayout.setVerticalGroup(
            frameMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        frameMedidas2.setPreferredSize(new java.awt.Dimension(500, 500));
        frameMedidas2.setSize(new java.awt.Dimension(500, 500));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel7.setText("Medidas PQRS");

        cbPqrsRespondidas2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPqrsRespondidas2ItemStateChanged(evt);
            }
        });

        jLabel8.setText("Ticket");

        taMedidaTomada.setColumns(20);
        taMedidaTomada.setRows(5);
        taMedidaTomada.setEnabled(false);
        jScrollPane3.setViewportView(taMedidaTomada);

        btFinalizarMedida.setText("Registrar como finalizada");
        btFinalizarMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarMedidaActionPerformed(evt);
            }
        });

        jLabel9.setText("Medida");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cbPqrsRespondidas2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cbMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(156, 156, 156))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btFinalizarMedida)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPqrsRespondidas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btFinalizarMedida)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameMedidas2Layout = new javax.swing.GroupLayout(frameMedidas2.getContentPane());
        frameMedidas2.getContentPane().setLayout(frameMedidas2Layout);
        frameMedidas2Layout.setHorizontalGroup(
            frameMedidas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameMedidas2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        frameMedidas2Layout.setVerticalGroup(
            frameMedidas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameMedidas2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("Administrar PQRS");

        taRespuesta.setColumns(20);
        taRespuesta.setRows(5);
        jScrollPane1.setViewportView(taRespuesta);

        jLabel1.setText("Respuesta");

        btResponder.setText("Responder");
        btResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResponderActionPerformed(evt);
            }
        });

        btMedidasRegistrar.setText("Registrar Medidas");
        btMedidasRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedidasRegistrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingreso de medidas a tomar para PQRS respondidos");

        btMedidasConsultar.setText("Consultar Medidas");
        btMedidasConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedidasConsultarActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingreso de medidas a tomar para PQRS respondidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(130, 130, 130))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbPqrs, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(btMedidasRegistrar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btResponder))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(btMedidasConsultar)
                                .addGap(0, 71, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbPqrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btResponder)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btMedidasRegistrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btMedidasConsultar))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResponderActionPerformed
        // TODO add your handling code here:
        try{
            int ticket = Integer.parseInt(cbPqrs.getSelectedItem().toString());
            String msj = emp.registrarRespuestaPqrs(ticket, id_Adm, taRespuesta.getText());
            JOptionPane.showMessageDialog(this, msj, "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "El item seleccionado no es un ticket valido", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btResponderActionPerformed

    private void btMedidasRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedidasRegistrarActionPerformed
        // TODO add your handling code here:
        ArrayList<String> respondidas = new ArrayList();
        try {
            respondidas = emp.PqrsRespondidas();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        Iterator iter = respondidas.iterator();
            while (iter.hasNext()) {
                String tmp = iter.next().toString();
                this.cbPqrsRespondidas.addItem(tmp);
            }
            
        frameMedidas.setLocationRelativeTo(null);
        frameMedidas.setVisible(true);
        
    }//GEN-LAST:event_btMedidasRegistrarActionPerformed

    private void btRegMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegMedidaActionPerformed
        // TODO add your handling code here:
        try{
            int ticket = Integer.parseInt(cbPqrsRespondidas.getSelectedItem().toString());
            String msj = emp.agregarMedidaPqrs(ticket, taMedidaATomar.getText());
            JOptionPane.showMessageDialog(this, msj, "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "El item seleccionado no es un ticket valido", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btRegMedidaActionPerformed

    private void btMedidasConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedidasConsultarActionPerformed
        // TODO add your handling code here:
        ArrayList<String> respondidas = new ArrayList();
        try {
            respondidas = emp.PqrsRespondidas();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        Iterator iter = respondidas.iterator();
            while (iter.hasNext()) {
                String tmp = iter.next().toString();
                this.cbPqrsRespondidas2.addItem(tmp);
            }
            
        frameMedidas2.setLocationRelativeTo(null);
        frameMedidas2.setVisible(true);
        
    }//GEN-LAST:event_btMedidasConsultarActionPerformed

    private void btFinalizarMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarMedidaActionPerformed
        // TODO add your handling code here:
        int ticket, medida;
        
        try{
            ticket = Integer.parseInt((String) cbPqrsRespondidas2.getSelectedItem());
            medida = Integer.parseInt((String) cbMedidas.getSelectedItem());
            emp.medidaRealizada(medida, ticket);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "El item seleccionado no es una medida valido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btFinalizarMedidaActionPerformed

    private void cbPqrsRespondidas2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPqrsRespondidas2ItemStateChanged
        
        int ticket = Integer.parseInt((String) cbPqrsRespondidas2.getSelectedItem());
        
        ArrayList<String> medidas = new ArrayList();
        try {
            medidas = emp.consultarMedidasPqrs(ticket);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        Iterator iter2 = medidas.iterator();
            while (iter2.hasNext()) {
                String tmp = iter2.next().toString();
                this.cbMedidas.addItem(tmp);
            }
    }//GEN-LAST:event_cbPqrsRespondidas2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PqrsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PqrsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PqrsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PqrsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PqrsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizarMedida;
    private javax.swing.JButton btMedidasConsultar;
    private javax.swing.JButton btMedidasRegistrar;
    private javax.swing.JButton btRegMedida;
    private javax.swing.JButton btResponder;
    private javax.swing.JComboBox cbMedidas;
    private javax.swing.JComboBox cbPqrs;
    private javax.swing.JComboBox cbPqrsRespondidas;
    private javax.swing.JComboBox cbPqrsRespondidas2;
    private javax.swing.JFrame frameMedidas;
    private javax.swing.JFrame frameMedidas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taMedidaATomar;
    private javax.swing.JTextArea taMedidaTomada;
    private javax.swing.JTextArea taRespuesta;
    // End of variables declaration//GEN-END:variables
}
