/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DAO.Conexion;
import DAO.DAOEstacionImpl;
import Mapeo.Estacion;
import java.awt.BorderLayout;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PORTATIL
 */
public class CrudAsigna extends javax.swing.JFrame {

    /**
     * Creates new form CrudAsigna
     */
    
    private List<String> recorrido = new ArrayList<String>();
    private String recorrido_ruta = "";
    
    public void agregarRecorrido(String reco){
        this.recorrido.add(reco);
    }
    
    public void borrarRecorrido(String reco){
        this.recorrido.remove(reco);
    }
    
    public List<String> getRecorrido(){
        return this.recorrido;
    }
    
    public CrudAsigna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ruta_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Asignar Recorrido ruta");

        jLabel2.setText("Ruta Id.");

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Asignar Recorrido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addComponent(ruta_id, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(102, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruta_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        
        DAOEstacionImpl mi_estacion = new DAOEstacionImpl();

        if (ruta_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor digite el id de la ruta que quiere asiganar");
        }else if (recorrido_ruta.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor asigne el recorrido de la ruta antes de continuar");
        }else{

            try {

                String estado_insersion = mi_estacion.registrar_asignacion(ruta_id.getText(), recorrido_ruta);
                JOptionPane.showMessageDialog(null, estado_insersion);
                
                if(estado_insersion.equalsIgnoreCase("Insersion exitosa")){
                    ruta_id.setText("");
                    recorrido_ruta = "";
                }                


            } catch (Exception ex) {
                //Logger.getLogger(CrudEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }

        }
        
    }//GEN-LAST:event_guardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Conexion conect = new Conexion();
        conect.conectar();
        String path = null;

        try {
            path = new java.io.File(".").getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(CrudEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            //System.out.println(path + "\\src\\Vista\\Empleados.jasper");
            JasperReport reporte = JasperCompileManager.compileReport(path + "\\src\\Reportes\\Asignacion_Rutas.jrxml");
            JasperPrint print = JasperFillManager.fillReport(reporte, null, conect.getConexion());

            JasperViewer jasperViewer = new JasperViewer(print);
            jasperViewer.setVisible(true);

            conect.cerrar();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        getRecorrido().clear();//Al abrir el panel borro todo lo que exista en la lista recorrido
        DAOEstacionImpl mi_estacion = new DAOEstacionImpl();
        List<String> estaciones = new ArrayList<String>();
        List<JRadioButton> botones = new ArrayList<JRadioButton>();
        
        String recorrido_old = "";
        
        if (ruta_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor digite el id de la ruta que quiere asiganar");
        }else{

            try {
                estaciones = mi_estacion.listarEstaciones();//traigo todos los administradores que hay en el sistema

                if (estaciones.isEmpty()) {
                    //estaciones.add("No existen Estaciones en la BD");//seteo la posicion cero por si no hay datos
                    JOptionPane.showMessageDialog(null, "No existen estaciones en la base de datos");
                    guardar.setEnabled(false);
                }else{
                    Iterator iter = estaciones.iterator();
                    while (iter.hasNext()) {

                        String tmp = iter.next().toString();
                        //JOptionPane.showMessageDialog(null, tmp);
                        String[] estacion = tmp.split("-");
                        //String[] coordenadas = array_estacion[2].split("-");
                        //array_estacion [0]: id_estacion
                        //array_estacion [1]: estacion_nombre
                        //array_estacion [2]: estacion_ubicacion en X
                        //array_estacion [3]: estacion_ubicacion en Y

                        JRadioButton botoncito = new JRadioButton(estacion[0]+"-"+estacion[1]);
                        botoncito.setName(estacion[0]+"-"+estacion[1]);
                        botoncito.setBounds(Integer.parseInt(estacion[2])-20, Integer.parseInt(estacion[3])-20, 100, 20);
                        botones.add(botoncito);

                    }
                    
                    recorrido_old = mi_estacion.get_asignacion(ruta_id.getText());
                    //JOptionPane.showMessageDialog(null, recorrido_old);
                    
                    if(!recorrido_old.equals("")){

                        String[] tmp_select = recorrido_old.split("-");
                        
                        //JOptionPane.showMessageDialog(null, tmp_select);
                        
                        Estacion mi_tmp_estacion = new Estacion();
                        String id_estacion_nombre = "";

                        for(int i=0; i<tmp_select.length;i++){
                            
                            agregarRecorrido(tmp_select[i]);
                            //JOptionPane.showMessageDialog(null, tmp_select.length);
                            
                            mi_tmp_estacion = mi_estacion.buscar(Integer.parseInt(tmp_select[i]));
                            id_estacion_nombre = mi_tmp_estacion.getEstacionId() + "-" + mi_tmp_estacion.getEstacionNombre();
                            
                            //JOptionPane.showMessageDialog(null, id_estacion_nombre);
                            
                            
                            Iterator www = botones.iterator();
                            while (www.hasNext()) {

                                JRadioButton radioButtonSelect;
                                radioButtonSelect = (JRadioButton) www.next();
                                
                                if(radioButtonSelect.getName().equals(id_estacion_nombre)){
                                    radioButtonSelect.setSelected(true);
                                    botones.add(radioButtonSelect);
                                    break;
                                }

                            }
                            
                            //JOptionPane.showMessageDialog(null, tmp_select.length);
                        }
                    }
                }


            } catch (Exception ex) {
                //Logger.getLogger(CrudEstacion.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }

            MapaAsigna t = new MapaAsigna();

            JPanel bgPanel = new BgPanelAsigna();

            Iterator ite = botones.iterator();
            while (ite.hasNext()) {

                JRadioButton radioButton;
                radioButton = (JRadioButton) ite.next();
                bgPanel.setLayout(null);
                bgPanel.add(radioButton);

            }

            JButton boton = new JButton("Guardar");
            bgPanel.setLayout(null);
            boton.setBounds(0, 0, 100, 20);
            bgPanel.add(boton);

            t.setContentPane(bgPanel);
            t.setExtendedState(MAXIMIZED_BOTH);
            t.setDefaultCloseOperation(HIDE_ON_CLOSE);

            t.setVisible(true);

            boton.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {

                    if(getRecorrido().isEmpty()){
                        JOptionPane.showMessageDialog(null, "No ha asignado ninguna estación al recorrido de la ruta. Debe asignarlo antes de salir.");
                    }else{

                        String tmp="";
                        Iterator i = getRecorrido().iterator();
                        while (i.hasNext()) {

                            tmp = i.next().toString();

                            if(!i.hasNext()){
                                recorrido_ruta += tmp;
                            }else{
                                recorrido_ruta += tmp+"-";
                            }
                        }
                        
                        

                        //JOptionPane.showMessageDialog(null, recorrido_ruta);
                        t.setVisible(false);
                    }

                }

            });

            Iterator it = botones.iterator();
            while (it.hasNext()) {

                JRadioButton radioButton;
                radioButton = (JRadioButton) it.next();
                String[] estacion_id_nombre = radioButton.getName().split("-");

                radioButton.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        if (evt.getSource() == radioButton) {

                            if (radioButton.isSelected()) {
                                agregarRecorrido(estacion_id_nombre[0]);
                                //JOptionPane.showMessageDialog(null, estacion_id_nombre[0]+estacion_id_nombre[1]);
                                //JOptionPane.showMessageDialog(null, getRecorrido());

                            }else{
                                //JOptionPane.showMessageDialog(null, "pailas");
                                borrarRecorrido(estacion_id_nombre[0]);

                            }

                        }

                    }

                });

            }
        }
        
        
        
        
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudAsigna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudAsigna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudAsigna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudAsigna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudAsigna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ruta_id;
    // End of variables declaration//GEN-END:variables
}
