/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DAO.Conexion;
import DAO.DAOTarjetaImpl;
import DAO.DAOUsuarioImpl;
import Mapeo.Tarjeta;
import Mapeo.Usuario;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Univalle_F
 */
public class CrudUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CrudUsuario() {
        initComponents();
    }
    
    public void setCampos() {
        usuario_id.setText("");
        usuario_nombre.setText("");;
        usuario_telefono.setText("");
        tarjeta_id.setText("");
        tarjeta_saldo.setText("");
    }

    public boolean validaCampos() {

        boolean valida = false;

        if (usuario_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor dígite la identificación del usuario");
        } else if (usuario_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor dígite el nombre del usuario");
        } else if (usuario_telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor dígite el telefono del usuario");
        } else {
            valida = true;
        }

        return valida;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        eliminarUsuario = new javax.swing.JButton();
        CrearUsuario = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        consultarUsuarios = new javax.swing.JButton();
        ListarUsuarios = new javax.swing.JButton();
        CrudUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usuario_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usuario_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usuario_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tarjeta_id = new javax.swing.JTextField();
        tarjeta_saldo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tarjeta_estado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eliminarUsuario.setText("Eliminar");
        eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUsuarioActionPerformed(evt);
            }
        });

        CrearUsuario.setText("Guardar");
        CrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        consultarUsuarios.setText("Consultar");
        consultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUsuariosActionPerformed(evt);
            }
        });

        ListarUsuarios.setText("Listar");
        ListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(salir)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(eliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addGap(136, 136, 136)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(eliminarUsuario)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(CrearUsuario)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        CrudUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CrudUsuario.setText("Usuario");

        jLabel2.setText("Identificacion Empleado");

        usuario_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_idActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        usuario_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_nombreActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefono");

        usuario_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_telefonoActionPerformed(evt);
            }
        });

        jLabel5.setText("Id. Tarjeta");

        tarjeta_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjeta_idActionPerformed(evt);
            }
        });

        tarjeta_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjeta_saldoActionPerformed(evt);
            }
        });

        jLabel6.setText("Saldo Tarjeta");

        jLabel7.setText("Estado");

        tarjeta_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVO", "INACTIVO" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tarjeta_id, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tarjeta_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(usuario_telefono)
                    .addComponent(tarjeta_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(usuario_nombre)
                    .addComponent(usuario_id))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarjeta_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarjeta_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarjeta_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrudUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrudUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUsuarioActionPerformed
        // TODO add your handling code here:
        DAOUsuarioImpl mi_usuario = new DAOUsuarioImpl();
        DAOTarjetaImpl tarjeta = new DAOTarjetaImpl();

        if (tarjeta_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor digite el id de la tarjeta");
        }else{
            
            try {
                if (!tarjeta.existe(Integer.parseInt(tarjeta_id.getText()))) {
                    JOptionPane.showMessageDialog(null, "La tarjeta que busca no existe");
                }else{

                    Tarjeta mi_tarjeta = tarjeta.buscar(Integer.parseInt(tarjeta_id.getText()));
                    String estado_tarjeta = tarjeta.eliminar(mi_tarjeta.getTarjetaPin());

                    JOptionPane.showMessageDialog(null, estado_tarjeta);

                    if (estado_tarjeta.equalsIgnoreCase("eliminación exitosa")) {

                        String estado = mi_usuario.eliminar(mi_tarjeta.getUsuario().getUsuarioId());
                        JOptionPane.showMessageDialog(null, estado);

                        if(estado.equalsIgnoreCase("eliminación exitosa")){

                            setVisible(false);
                            setCampos();
                            setVisible(true);

                        }

                    }

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_eliminarUsuarioActionPerformed

    private void CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioActionPerformed
        // TODO add your handling code here:
        DAOUsuarioImpl mi_usuario = new DAOUsuarioImpl();
        
        if (validaCampos()) {
            try {

                String estado = mi_usuario.registrar(usuario_id.getText(), usuario_nombre.getText(),usuario_telefono.getText());
                JOptionPane.showMessageDialog(null, estado);

                if (estado.equalsIgnoreCase("Insersion exitosa")) {
                    setVisible(false);
                    setCampos();
                    setVisible(true);
                    
                    tarjeta_estado.setEnabled(true);
                    tarjeta_saldo.setEnabled(true);//el saldo no lo puede tocar por este módulo
                    tarjeta_id.setEnabled(true);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }

    }//GEN-LAST:event_CrearUsuarioActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void consultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUsuariosActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        DAOUsuarioImpl usuario = new DAOUsuarioImpl();
        DAOTarjetaImpl tarjeta = new DAOTarjetaImpl();

        if (tarjeta_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor dígite el id de la tarjeta");
        }else {
            try {
                if(!tarjeta.existe(Integer.parseInt(tarjeta_id.getText()))){
                    JOptionPane.showMessageDialog(null, "La tarjeta que busca no existe");
                }else{

                    CrearUsuario.setEnabled(false);
                    eliminarUsuario.setEnabled(false);
                    
                    String usuario_a_ingresar = "";
                    Tarjeta mi_tarjeta = tarjeta.buscar(Integer.parseInt(tarjeta_id.getText()));
                    
                    if(mi_tarjeta.getUsuario().getUsuarioId().equals("0")){//si es usuario genérico, pide un usuario a actualizar
                        usuario_a_ingresar = JOptionPane.showInputDialog("Introduzca el usuario que desea personalizar: ");
                    }else{//si la tarjeta ya tiene un usuario, trae los datos de ese usuario
                        usuario_a_ingresar = mi_tarjeta.getUsuario().getUsuarioId();
                    }
                    
                  
                    Usuario miusuario = usuario.buscar(usuario_a_ingresar);
                    
                    if(usuario.existe(usuario_a_ingresar)){
                        
                        usuario_id.setText(miusuario.getUsuarioId());
                        usuario_nombre.setText(miusuario.getUsuarioNombre());
                        usuario_telefono.setText(miusuario.getUsuarioTelefono());
                        tarjeta_id.setText("" + mi_tarjeta.getTarjetaPin() + "");
                        tarjeta_saldo.setText(mi_tarjeta.getTarjetaSaldo());

                        String estado = "";

                        if (mi_tarjeta.isTarjetaEstado()) {
                            estado = "ACTIVO";
                        } else {
                            estado = "INACTIVO";
                        }

                        tarjeta_estado.setSelectedItem(estado);
                        tarjeta_saldo.setEnabled(false);//el saldo no lo puede tocar por este módulo
                        tarjeta_id.setEnabled(false);

                        this.setVisible(false);

                        JButton actualizar = new JButton("Actualizar");//creo un boton
                        actualizar.setSize(80, 29);
                        actualizar.reshape(110, 10, 100, 27);// x,y,largo,ancho
                        this.CrudUsuario.add(actualizar);
                        this.setVisible(true);

                        actualizar.addActionListener(new java.awt.event.ActionListener() {
                            @Override
                            public void actionPerformed(java.awt.event.ActionEvent evt) {

                                String id_usuario_old = miusuario.getUsuarioId();

                                try {

                                    if (validaCampos()) {

                                        boolean estado_tarjeta = false;
                                        if (tarjeta_estado.getSelectedItem().toString().equalsIgnoreCase("ACTIVO")) {
                                            estado_tarjeta = true;
                                        }

                                        String estado_update_usuario = usuario.modificar(id_usuario_old, usuario_id.getText(), usuario_nombre.getText(), usuario_telefono.getText());
                                        String estado_update_tarjeta = tarjeta.modificar(Integer.parseInt(tarjeta_id.getText()), usuario_id.getText(), id_usuario_old, tarjeta_saldo.getText(), estado_tarjeta);

                                        
                                        JOptionPane.showMessageDialog(null, estado_update_usuario + " de usuario");
                                        JOptionPane.showMessageDialog(null, estado_update_tarjeta + " de tarjeta");

                                        if (estado_update_tarjeta.equalsIgnoreCase("actualización exitosa") && estado_update_usuario.equalsIgnoreCase("actualización exitosa")) {

                                            //System.exit(0);
                                            CrudUsuario.remove(actualizar);
                                            setVisible(false);
                                            setCampos();

                                            CrearUsuario.setEnabled(true);
                                            eliminarUsuario.setEnabled(true);
                                            tarjeta_saldo.setEnabled(true);//el saldo no lo puede tocar por este módulo
                                            tarjeta_id.setEnabled(true);

                                            setVisible(true);

                                        }
                                    }

                                } catch (Exception ex) {
                                    Logger.getLogger(CrudEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                                }

                            }
                        });
                    
                    }else{
                        JOptionPane.showMessageDialog(null, "El usuario no existe, debe crearlo primero.");
                        setCampos();
                        CrearUsuario.setEnabled(true);
                        eliminarUsuario.setEnabled(true);
                        tarjeta_saldo.setEnabled(true);//el saldo no lo puede tocar por este módulo
                        tarjeta_id.setEnabled(true);
                        
                        tarjeta_estado.setEnabled(false);
                        tarjeta_saldo.setEnabled(false);//el saldo no lo puede tocar por este módulo
                        tarjeta_id.setEnabled(false);
                        
                    }

                    
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_consultarUsuariosActionPerformed

    private void ListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuariosActionPerformed
        // TODO add your handling code here:

        Conexion conect = new Conexion();
        conect.conectar();
        String path = null;

        try {
            path = new java.io.File(".").getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(CrudEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            //System.out.println(path + "\\src\\Vista\\Empleados.jasper");

            JasperReport reporte = JasperCompileManager.compileReport(path + "\\src\\Reportes\\Usuarios.jrxml");
            JasperPrint print = JasperFillManager.fillReport(reporte, null, conect.getConexion());

            JasperViewer jasperViewer = new JasperViewer(print);
            jasperViewer.setVisible(true);

            conect.cerrar();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ListarUsuariosActionPerformed

    private void usuario_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_idActionPerformed

    private void usuario_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_nombreActionPerformed

    private void usuario_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_telefonoActionPerformed

    private void tarjeta_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjeta_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjeta_idActionPerformed

    private void tarjeta_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjeta_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjeta_saldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearUsuario;
    private javax.swing.JLabel CrudUsuario;
    private javax.swing.JButton ListarUsuarios;
    private javax.swing.JButton consultarUsuarios;
    private javax.swing.JButton eliminarUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox tarjeta_estado;
    private javax.swing.JTextField tarjeta_id;
    private javax.swing.JTextField tarjeta_saldo;
    private javax.swing.JTextField usuario_id;
    private javax.swing.JTextField usuario_nombre;
    private javax.swing.JTextField usuario_telefono;
    // End of variables declaration//GEN-END:variables
}
