/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DAO.DAOEmpleadoImpl;
import DAO.DAOTarjetaImpl;
import DAO.DAOTurnoImpl;
import DAO.DAOUsuarioImpl;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Univalle_F
 */
public class Principal extends javax.swing.JFrame {
    
    private String empleado_logeado;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    public String getUserLogeado() {
        return empleado_logeado;
    }
    
    public void setUserLogeado(String id_empleado) {
        this.empleado_logeado = id_empleado;
    }
    
    public void moduloApp(int rol){
    
        switch (rol) {

            case 1://conductor

                usuario.setVisible(false);
                auxiliar.setVisible(false);
                gerente.setVisible(false);
                directorOp.setVisible(false);
                administradorE.setVisible(false);
                
                break;
            case 2://auxiliar

                usuario.setVisible(false);
                gerente.setVisible(false);
                conductor.setVisible(false);
                directorOp.setVisible(false);
                administradorE.setVisible(false);
                
                break;
            case 3://administrador
                
                usuario.setVisible(false);
                auxiliar.setVisible(false);
                gerente.setVisible(false);
                conductor.setVisible(false);
                directorOp.setVisible(false);
                break;
            case 4://director operativo
                usuario.setVisible(false);
                auxiliar.setVisible(false);
                gerente.setVisible(false);
                conductor.setVisible(false);
                administradorE.setVisible(false);
                break;
            case 5://gerente

                break;
            default:
                auxiliar.setVisible(false);
                gerente.setVisible(false);
                conductor.setVisible(false);
                directorOp.setVisible(false);
                administradorE.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        directorOp = new javax.swing.JPanel();
        btCrudBus = new javax.swing.JButton();
        btCrudEmp = new javax.swing.JButton();
        btCrudRutaRecorrido = new javax.swing.JButton();
        btCrudEstacion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btCrudRuta = new javax.swing.JButton();
        btCrudTurno = new javax.swing.JButton();
        btAsignarTurno = new javax.swing.JButton();
        usuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btAbordar = new javax.swing.JButton();
        btMostrarRuta = new javax.swing.JButton();
        btPqrsUsr = new javax.swing.JButton();
        conductor = new javax.swing.JPanel();
        btConsultarTurno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        auxiliar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btRecargarT = new javax.swing.JButton();
        btVenderT = new javax.swing.JButton();
        btPersonalizarT = new javax.swing.JButton();
        btPqrsInic = new javax.swing.JButton();
        gerente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btReportes = new javax.swing.JButton();
        administradorE = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btAdmPqrs = new javax.swing.JButton();
        btAdmCrudAux = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Menu Principal");

        btCrudBus.setText("CRUD BUS");
        btCrudBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrudBusActionPerformed(evt);
            }
        });

        btCrudEmp.setText("CRUD EMPLEADO");
        btCrudEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrudEmpActionPerformed(evt);
            }
        });

        btCrudRutaRecorrido.setText("CRUD RECORRIDO RUTA");
        btCrudRutaRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrudRutaRecorridoActionPerformed(evt);
            }
        });

        btCrudEstacion.setText("CRUD ESTACION");
        btCrudEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrudEstacionActionPerformed(evt);
            }
        });

        jLabel4.setText(" Director Operativo");

        btCrudRuta.setText("CRUD RUTA");
        btCrudRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrudRutaActionPerformed(evt);
            }
        });

        btCrudTurno.setText("CRUD TURNO");
        btCrudTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrudTurnoActionPerformed(evt);
            }
        });

        btAsignarTurno.setText("Asignar turno");
        btAsignarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsignarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout directorOpLayout = new javax.swing.GroupLayout(directorOp);
        directorOp.setLayout(directorOpLayout);
        directorOpLayout.setHorizontalGroup(
            directorOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(directorOpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(directorOpLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(directorOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAsignarTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCrudRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCrudEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCrudRutaRecorrido, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(btCrudBus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCrudEstacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCrudTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        directorOpLayout.setVerticalGroup(
            directorOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(directorOpLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCrudEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCrudBus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCrudRuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCrudRutaRecorrido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCrudEstacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCrudTurno)
                .addGap(18, 18, 18)
                .addComponent(btAsignarTurno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Usuario");

        btAbordar.setText("Abordar Ruta");
        btAbordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbordarActionPerformed(evt);
            }
        });

        btMostrarRuta.setText("Mostrar Ruta");
        btMostrarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarRutaActionPerformed(evt);
            }
        });

        btPqrsUsr.setText("Consulta PQRS");
        btPqrsUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPqrsUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usuarioLayout = new javax.swing.GroupLayout(usuario);
        usuario.setLayout(usuarioLayout);
        usuarioLayout.setHorizontalGroup(
            usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(usuarioLayout.createSequentialGroup()
                        .addComponent(btAbordar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMostrarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPqrsUsr))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        usuarioLayout.setVerticalGroup(
            usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAbordar)
                    .addComponent(btMostrarRuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPqrsUsr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btConsultarTurno.setText("Consultar Turno");
        btConsultarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarTurnoActionPerformed(evt);
            }
        });

        jLabel3.setText("Conductor");

        javax.swing.GroupLayout conductorLayout = new javax.swing.GroupLayout(conductor);
        conductor.setLayout(conductorLayout);
        conductorLayout.setHorizontalGroup(
            conductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conductorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(conductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conductorLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conductorLayout.createSequentialGroup()
                        .addComponent(btConsultarTurno)
                        .addContainerGap())))
        );
        conductorLayout.setVerticalGroup(
            conductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conductorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultarTurno)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel5.setText("Auxiliar Servicio al Cliente");

        btRecargarT.setText("Recargar");
        btRecargarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecargarTActionPerformed(evt);
            }
        });

        btVenderT.setText("Vender Tarjeta");
        btVenderT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVenderTActionPerformed(evt);
            }
        });

        btPersonalizarT.setText("Personalizar");
        btPersonalizarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPersonalizarTActionPerformed(evt);
            }
        });

        btPqrsInic.setText("PQRS");
        btPqrsInic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPqrsInicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout auxiliarLayout = new javax.swing.GroupLayout(auxiliar);
        auxiliar.setLayout(auxiliarLayout);
        auxiliarLayout.setHorizontalGroup(
            auxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(auxiliarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(auxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btVenderT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(auxiliarLayout.createSequentialGroup()
                        .addGroup(auxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btRecargarT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPersonalizarT, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPqrsInic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        auxiliarLayout.setVerticalGroup(
            auxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(auxiliarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(auxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRecargarT)
                    .addComponent(btPersonalizarT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVenderT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPqrsInic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Gerente General");

        btReportes.setText("Reportes");
        btReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gerenteLayout = new javax.swing.GroupLayout(gerente);
        gerente.setLayout(gerenteLayout);
        gerenteLayout.setHorizontalGroup(
            gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btReportes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gerenteLayout.setVerticalGroup(
            gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btReportes)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel6.setText("Administrador estación");

        btAdmPqrs.setText("PQRS Administrar");
        btAdmPqrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmPqrsActionPerformed(evt);
            }
        });

        btAdmCrudAux.setText("Auxiliares Servicio al Cliente");
        btAdmCrudAux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmCrudAuxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout administradorELayout = new javax.swing.GroupLayout(administradorE);
        administradorE.setLayout(administradorELayout);
        administradorELayout.setHorizontalGroup(
            administradorELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administradorELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(administradorELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(administradorELayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(administradorELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAdmCrudAux)
                            .addComponent(btAdmPqrs))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        administradorELayout.setVerticalGroup(
            administradorELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administradorELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAdmPqrs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdmCrudAux)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(auxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(directorOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(administradorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directorOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(auxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(administradorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRecargarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecargarTActionPerformed
        // TODO add your handling code here:
        
    String id_tarjeta = "";
    String saldo = "";

    DAOTarjetaImpl tarjeta = new DAOTarjetaImpl();
    
    do{
        id_tarjeta = JOptionPane.showInputDialog("Introduce el id de la tarjeta a recargar: ");
        saldo = JOptionPane.showInputDialog("Introduce la cantidad de dinero a recargar: ");
    
    }while(id_tarjeta.equals("") && saldo.equals(""));

        try {
            String mensaje_recarga = tarjeta.recarga(Integer.parseInt(id_tarjeta), saldo, this.getUserLogeado());
            
            //OptionPane.showMessageDialog(null, mensaje_recarga);
            
            if (mensaje_recarga.equalsIgnoreCase("Recarga exitosa")) {
                
                JOptionPane.showMessageDialog(null, mensaje_recarga);
                
                id_tarjeta = "";
                saldo = "";
            }else{
                JOptionPane.showMessageDialog(null, mensaje_recarga);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            //Logger.getLogger(CrudEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }//GEN-LAST:event_btRecargarTActionPerformed

    private void btPqrsInicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPqrsInicActionPerformed
        // TODO add your handling code here:
        PQRS pqrsFrame = new PQRS();
        pqrsFrame.setLocationRelativeTo(null);
        pqrsFrame.setUserLogeado(getUserLogeado());
        pqrsFrame.setVisible(true);
    }//GEN-LAST:event_btPqrsInicActionPerformed

    private void btCrudEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrudEmpActionPerformed
        // TODO add your handling code here:
        CrudEmpleado ni_crud = new CrudEmpleado();
        ni_crud.setLocationRelativeTo(null);
        ni_crud.setVisible(true);
    }//GEN-LAST:event_btCrudEmpActionPerformed

    private void btCrudEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrudEstacionActionPerformed
        // TODO add your handling code here:
        
        CrudEstacion mi_login = new CrudEstacion();
        mi_login.setLocationRelativeTo(null);
        mi_login.setVisible(true);
        
        
    }//GEN-LAST:event_btCrudEstacionActionPerformed

    private void btCrudBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrudBusActionPerformed
        // TODO add your handling code here:
        
        CrudBus mi_bus = new CrudBus();
        mi_bus.setLocationRelativeTo(null);
        mi_bus.setVisible(true);
        
    }//GEN-LAST:event_btCrudBusActionPerformed

    private void btCrudRutaRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrudRutaRecorridoActionPerformed
        // TODO add your handling code here:
        
        CrudAsigna mi_login = new CrudAsigna();
        mi_login.setLocationRelativeTo(null);
        mi_login.setVisible(true);
        
    }//GEN-LAST:event_btCrudRutaRecorridoActionPerformed

    private void btAsignarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsignarTurnoActionPerformed
        // TODO add your handling code here:
       
        AsignarTurnos mi_asigna_turno = new AsignarTurnos();
        mi_asigna_turno.setLocationRelativeTo(null);
        mi_asigna_turno.setVisible(true);
        
    }//GEN-LAST:event_btAsignarTurnoActionPerformed

    private void btCrudRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrudRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCrudRutaActionPerformed

    private void btVenderTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVenderTActionPerformed
        // TODO add your handling code here:
        
        DAOTarjetaImpl tarjeta = new DAOTarjetaImpl();

        try {
            String mensaje_venta = tarjeta.venderTarjeta(this.getUserLogeado());
            JOptionPane.showMessageDialog(null, mensaje_venta);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btVenderTActionPerformed

    private void btPersonalizarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPersonalizarTActionPerformed
        // TODO add your handling code here:
        CrudUsuario mi_usuario = new CrudUsuario();
        mi_usuario.setLocationRelativeTo(null);
        mi_usuario.setVisible(true);//muestro la interfaz de reserva
    }//GEN-LAST:event_btPersonalizarTActionPerformed

    private void btAbordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbordarActionPerformed
        // TODO add your handling code here:
        
        String id_tarjeta = "";
        String id_ruta = "";

        DAOTarjetaImpl tarjeta = new DAOTarjetaImpl();

        do {
            id_tarjeta = JOptionPane.showInputDialog("Introduce el id de la tarjeta: ");
            id_ruta = JOptionPane.showInputDialog("Introduce el id de la ruta a la cual ingresas: ");

        } while (id_tarjeta.equals(""));
        
        try {
            String mensaje = tarjeta.descuenta(Integer.parseInt(id_tarjeta),id_ruta);
            JOptionPane.showMessageDialog(null, mensaje);
            id_tarjeta = "";

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btAbordarActionPerformed

    private void btConsultarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarTurnoActionPerformed
        // TODO add your handling code here:
        DAOEmpleadoImpl empleado = new DAOEmpleadoImpl();
        String id_empleado = "";

        do {
            id_empleado = JOptionPane.showInputDialog("Introduce el id del conductor: ");

        } while (id_empleado.equals(""));

        try {
            String mensaje = empleado.consultarTurno(id_empleado);

            if (!mensaje.equalsIgnoreCase("El empleado no tiene turno asignado")) {

                JOptionPane.showMessageDialog(null, mensaje);
                id_empleado = "";

            } else {
                JOptionPane.showMessageDialog(null, mensaje);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btConsultarTurnoActionPerformed

    private void btCrudTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrudTurnoActionPerformed
        // TODO add your handling code here:
        
        CrudTurno mi_login = new CrudTurno();
        mi_login.setLocationRelativeTo(null);
        mi_login.setVisible(true);
        
    }//GEN-LAST:event_btCrudTurnoActionPerformed

    private void btMostrarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarRutaActionPerformed
        // TODO add your handling code here:
        
        MuestraRuta mi_login = new MuestraRuta();
        mi_login.setLocationRelativeTo(null);
        mi_login.setVisible(true);
    }//GEN-LAST:event_btMostrarRutaActionPerformed

    private void btReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReportesActionPerformed
        // TODO add your handling code here:
        
        Reportes mi_login = new Reportes();
        mi_login.setLocationRelativeTo(null);
        mi_login.setVisible(true);
    }//GEN-LAST:event_btReportesActionPerformed

    private void btAdmCrudAuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmCrudAuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdmCrudAuxActionPerformed

    private void btAdmPqrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmPqrsActionPerformed
        // TODO add your handling code here:
        PqrsAdmin sesion = new PqrsAdmin();
        sesion.setId(empleado_logeado);
        
        sesion.setLocationRelativeTo(null);
        sesion.setVisible(true);
        
    }//GEN-LAST:event_btAdmPqrsActionPerformed

    private void btPqrsUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPqrsUsrActionPerformed
        // TODO add your handling code here:
        UsuarioConsultaPqrs consulta = new UsuarioConsultaPqrs();
        consulta.setUserLogeado(empleado_logeado);
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);
        
    }//GEN-LAST:event_btPqrsUsrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel administradorE;
    private javax.swing.JPanel auxiliar;
    private javax.swing.JButton btAbordar;
    private javax.swing.JButton btAdmCrudAux;
    private javax.swing.JButton btAdmPqrs;
    private javax.swing.JButton btAsignarTurno;
    private javax.swing.JButton btConsultarTurno;
    private javax.swing.JButton btCrudBus;
    private javax.swing.JButton btCrudEmp;
    private javax.swing.JButton btCrudEstacion;
    private javax.swing.JButton btCrudRuta;
    private javax.swing.JButton btCrudRutaRecorrido;
    private javax.swing.JButton btCrudTurno;
    private javax.swing.JButton btMostrarRuta;
    private javax.swing.JButton btPersonalizarT;
    private javax.swing.JButton btPqrsInic;
    private javax.swing.JButton btPqrsUsr;
    private javax.swing.JButton btRecargarT;
    private javax.swing.JButton btReportes;
    private javax.swing.JButton btVenderT;
    private javax.swing.JPanel conductor;
    private javax.swing.JPanel directorOp;
    private javax.swing.JPanel gerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel usuario;
    // End of variables declaration//GEN-END:variables
}
