/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DAO.Conexion;
import DAO.DAOEstacionImpl;
import DAO.DAORutaImpl;
import Interfaces.DAOEstacion;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PORTATIL
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        
        DAOEstacionImpl estacion = new DAOEstacionImpl();
        DAORutaImpl ruta = new DAORutaImpl();
        List<String> rutas = new ArrayList();
        List<String> estaciones = new ArrayList();
        
        try {
            rutas = ruta.listar();

            Iterator iter = rutas.iterator();
            while (iter.hasNext()) {
                String tmp = iter.next().toString();
                this.cbRuta.addItem(tmp);
            }

        } catch (Exception ex) {
            //Logger.getLogger(CrudEstacion.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        
        try {
            estaciones = estacion.listarEstaciones();

            Iterator iter = estaciones.iterator();
            while (iter.hasNext()) {
                String tmp = iter.next().toString();
                this.cbEstacion.addItem(tmp);
            }

        } catch (Exception ex) {
            //Logger.getLogger(CrudEstacion.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btRPasajeros = new javax.swing.JButton();
        btRMovilizadosFechaRuta = new javax.swing.JButton();
        btRVentas = new javax.swing.JButton();
        btRPqrs = new javax.swing.JButton();
        btRBuses = new javax.swing.JButton();
        btRRutas = new javax.swing.JButton();
        btRPqrsMotivos = new javax.swing.JButton();
        btRSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbRuta = new javax.swing.JComboBox();
        cbEstacion = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jxDkFechaDesde = new org.jdesktop.swingx.JXDatePicker();
        jxDkFechaHasta = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 335));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reoprtes del Sistema");

        btRPasajeros.setText("Pasajeros del Sistema");
        btRPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRPasajerosActionPerformed(evt);
            }
        });

        btRMovilizadosFechaRuta.setText("Movilizados por fecha y ruta");
        btRMovilizadosFechaRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRMovilizadosFechaRutaActionPerformed(evt);
            }
        });

        btRVentas.setText("Valor de tarjetas vendidas por estacion y fecha");
        btRVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRVentasActionPerformed(evt);
            }
        });

        btRPqrs.setText("PQRS");
        btRPqrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRPqrsActionPerformed(evt);
            }
        });

        btRBuses.setText("Buses del Sistema");
        btRBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRBusesActionPerformed(evt);
            }
        });

        btRRutas.setText("Rutas del Sistema");
        btRRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRRutasActionPerformed(evt);
            }
        });

        btRPqrsMotivos.setText("PQRS mas comunes");

        btRSalir.setText("Salir");
        btRSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Fechas");

        jLabel3.setText("Estación");

        jLabel4.setText("Ruta");

        jxDkFechaDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxDkFechaDesdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(btRVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRPqrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRPqrsMotivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRMovilizadosFechaRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbRuta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbEstacion, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jxDkFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jxDkFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btRSalir)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRPasajeros)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRMovilizadosFechaRuta)
                    .addComponent(jxDkFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jxDkFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRVentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRPqrs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRBuses))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRRutas)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRPqrsMotivos)
                    .addComponent(cbEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btRSalir)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRPqrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRPqrsActionPerformed
        // TODO add your handling code here:
        Conexion conect = new Conexion();
        conect.conectar();
        String path = null;
        String ts = new SimpleDateFormat("dd-MM-yyyy-HH.mm.ss").format(new java.util.Date());
        
        java.util.Date fecha1, fecha2;
        fecha1 = jxDkFechaDesde.getDate();
        fecha2 = jxDkFechaHasta.getDate();
        
        HashMap parametros = new HashMap<String, Object>();
        
        parametros.put("fecha1", fecha1);
        parametros.put("fecha2", fecha2);
        
        int index = cbEstacion.getSelectedIndex();
        String estacion = Integer.toString(index);
        String estacion_sql;
        
        if(index != 0){
            
            estacion_sql = "AND estacion pqrs_estacion = '"+ estacion +"'";
        }else{
            estacion = "";
            estacion_sql = "";
        }
        
        
        parametros.put("estacion_sql", estacion_sql);
        parametros.put("estacion", estacion);
        
        try {
            path = new java.io.File(".").getCanonicalPath();
        } catch (IOException ex) {
            System.out.println(ex);
        }

        try {

            String reporte = path + "\\src\\Reportes\\PQRS.jasper";
            String pdfName = path + "\\Reportes\\PQRS"+ ts +".pdf";
            JasperPrint print = JasperFillManager.fillReport(reporte, parametros, conect.getConexion());

            JasperViewer jasperViewer = new JasperViewer(print);
            jasperViewer.setVisible(true);
            JasperExportManager.exportReportToPdfFile(print, pdfName);

            conect.cerrar();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btRPqrsActionPerformed

    private void btRPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRPasajerosActionPerformed
        // TODO add your handling code here:
        Conexion conect = new Conexion();
        conect.conectar();
        String path = null;
        String ts = new SimpleDateFormat("dd-MM-yyyy-HH.mm.ss").format(new java.util.Date());
        
        try {
            path = new java.io.File(".").getCanonicalPath();
        } catch (IOException ex) {
            System.out.println(ex);
        }

        try {

            String reporte = path + "\\src\\Reportes\\Usuarios.jasper";
            String pdfName = path + "\\Reportes\\Usuarios"+ ts +".pdf";
            JasperPrint print = JasperFillManager.fillReport(reporte, null, conect.getConexion());

            JasperViewer jasperViewer = new JasperViewer(print);
            jasperViewer.setVisible(true);
            JasperExportManager.exportReportToPdfFile(print, pdfName);

            conect.cerrar();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btRPasajerosActionPerformed

    private void btRVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRVentasActionPerformed
        // TODO add your handling code here:
        
        Conexion conect = new Conexion();
        conect.conectar();
        String path = null;
        String ts = new SimpleDateFormat("dd-MM-yyyy-HH.mm.ss").format(new java.util.Date());
        java.util.Date fecha1, fecha2;
        fecha1 = jxDkFechaDesde.getDate();
        fecha2 = jxDkFechaHasta.getDate();
        
        Map parametros = new HashMap();
        parametros.put("fecha1", fecha1);
        parametros.put("fecha2", fecha2);
        
        try {
            path = new java.io.File(".").getCanonicalPath();
        } catch (IOException ex) {
            System.out.println (ex);
        }

        try {
            String reporte = path + "\\src\\Reportes\\TarjetasVendidas.jasper";
            String pdfName = path + "\\Reportes\\Usuarios"+ ts +".pdf";
            JasperPrint print = JasperFillManager.fillReport(reporte, parametros, conect.getConexion());

            JasperViewer jasperViewer = new JasperViewer(print);
            jasperViewer.setVisible(true);
            JasperExportManager.exportReportToPdfFile(print, pdfName);

            conect.cerrar();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btRVentasActionPerformed

    private void btRBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRBusesActionPerformed
        // TODO add your handling code here:
        
        Conexion conect = new Conexion();
        conect.conectar();
        String path = null;
        String ts = new SimpleDateFormat("dd-MM-yyyy-HH.mm.ss").format(new java.util.Date());

        try {
            path = new java.io.File(".").getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(CrudEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            String reporte = path +"\\src\\Reportes\\Buses.jasper";
            String pdfName = path + "\\Reportes\\Buses"+ ts +".pdf";
            JasperPrint print = JasperFillManager.fillReport(reporte, null, conect.getConexion());

            JasperViewer jasperViewer = new JasperViewer(print);
            jasperViewer.setVisible(true);
            JasperExportManager.exportReportToPdfFile(print, pdfName);

            conect.cerrar();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btRBusesActionPerformed

    private void btRRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRRutasActionPerformed
        // TODO add your handling code here:
        Conexion conect = new Conexion();
        conect.conectar();
        String path = null;
        String ts = new SimpleDateFormat("dd-MM-yyyy-HH.mm.ss").format(new java.util.Date());

        try {
            path = new java.io.File(".").getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(CrudEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            String reporte = path + "\\src\\Reportes\\Rutas.jasper";
            String pdfName = path + "\\Reportes\\Rutas"+ ts +".pdf";
            JasperPrint print = JasperFillManager.fillReport(reporte, null, conect.getConexion());

            JasperViewer jasperViewer = new JasperViewer(print);
            jasperViewer.setVisible(true);
            JasperExportManager.exportReportToPdfFile(print, pdfName);


            conect.cerrar();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btRRutasActionPerformed

    private void btRSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btRSalirActionPerformed

    private void btRMovilizadosFechaRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRMovilizadosFechaRutaActionPerformed
        // TODO add your handling code here:
        Conexion conect = new Conexion();
        conect.conectar();
        String path = null;
        String ts = new SimpleDateFormat("dd-MM-yyyy-HH.mm.ss").format(new java.util.Date());
        
        java.util.Date fecha1, fecha2;
        fecha1 = jxDkFechaDesde.getDate();
        fecha2 = jxDkFechaHasta.getDate();
        
        HashMap parametros = new HashMap<String, Object>();
        
        parametros.put("fecha1", fecha1);
        parametros.put("fecha2", fecha2);
        
        String ruta = (String)cbRuta.getSelectedItem();
        String ruta_sql;
        
        if(!ruta.equals("Seleccione ruta")){
            
            ruta_sql = "AND aborda_ruta = '"+ ruta +"'";
        }else{
            ruta = "";
            ruta_sql = "";
        }
        
        
        parametros.put("ruta_sql", ruta_sql);
        parametros.put("ruta", ruta);
        
        try {
            path = new java.io.File(".").getCanonicalPath();
        } catch (IOException ex) {
            System.out.println(ex);
        }

        try {

            String reporte = path + "\\src\\Reportes\\Pasajeros_movilizados.jasper";
            String pdfName = path + "\\Reportes\\Pasajeros_movilizados"+ ts +".pdf";
            JasperPrint print = JasperFillManager.fillReport(reporte, parametros, conect.getConexion());

            JasperViewer jasperViewer = new JasperViewer(print);
            jasperViewer.setVisible(true);
            JasperExportManager.exportReportToPdfFile(print, pdfName);

            conect.cerrar();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btRMovilizadosFechaRutaActionPerformed

    private void jxDkFechaDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxDkFechaDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxDkFechaDesdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRBuses;
    private javax.swing.JButton btRMovilizadosFechaRuta;
    private javax.swing.JButton btRPasajeros;
    private javax.swing.JButton btRPqrs;
    private javax.swing.JButton btRPqrsMotivos;
    private javax.swing.JButton btRRutas;
    private javax.swing.JButton btRSalir;
    private javax.swing.JButton btRVentas;
    private javax.swing.JComboBox cbEstacion;
    private javax.swing.JComboBox cbRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXDatePicker jxDkFechaDesde;
    private org.jdesktop.swingx.JXDatePicker jxDkFechaHasta;
    // End of variables declaration//GEN-END:variables
}
