package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Conductor generated by hbm2java
 */
public class Conductor  implements java.io.Serializable {


     private String conductorEmpleadoId;
     private Bus bus;
     private Empleado empleado;
     private Set<Turno> turnos = new HashSet<Turno>(0);

    public Conductor() {
    }

	
    public Conductor(Bus bus, Empleado empleado) {
        this.bus = bus;
        this.empleado = empleado;
    }
    public Conductor(Bus bus, Empleado empleado, Set<Turno> turnos) {
       this.bus = bus;
       this.empleado = empleado;
       this.turnos = turnos;
    }
   
    public String getConductorEmpleadoId() {
        return this.conductorEmpleadoId;
    }
    
    public void setConductorEmpleadoId(String conductorEmpleadoId) {
        this.conductorEmpleadoId = conductorEmpleadoId;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Set<Turno> getTurnos() {
        return this.turnos;
    }
    
    public void setTurnos(Set<Turno> turnos) {
        this.turnos = turnos;
    }




}


