package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * PqrsMedida generated by hbm2java
 */
public class PqrsMedida  implements java.io.Serializable {


     private PqrsMedidaId id;
     private Pqrs pqrs;
     private String pqrsMedidaDescrip;
     private String pqrsMedidaEstado;

    public PqrsMedida() {
    }

    public PqrsMedida(PqrsMedidaId id, Pqrs pqrs, String pqrsMedidaDescrip, String pqrsMedidaEstado) {
       this.id = id;
       this.pqrs = pqrs;
       this.pqrsMedidaDescrip = pqrsMedidaDescrip;
       this.pqrsMedidaEstado = pqrsMedidaEstado;
    }
   
    public PqrsMedidaId getId() {
        return this.id;
    }
    
    public void setId(PqrsMedidaId id) {
        this.id = id;
    }
    public Pqrs getPqrs() {
        return this.pqrs;
    }
    
    public void setPqrs(Pqrs pqrs) {
        this.pqrs = pqrs;
    }
    public String getPqrsMedidaDescrip() {
        return this.pqrsMedidaDescrip;
    }
    
    public void setPqrsMedidaDescrip(String pqrsMedidaDescrip) {
        this.pqrsMedidaDescrip = pqrsMedidaDescrip;
    }
    public String getPqrsMedidaEstado() {
        return this.pqrsMedidaEstado;
    }
    
    public void setPqrsMedidaEstado(String pqrsMedidaEstado) {
        this.pqrsMedidaEstado = pqrsMedidaEstado;
    }




}


