package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * Recarga generated by hbm2java
 */
public class Recarga  implements java.io.Serializable {


     private RecargaId id;
     private Estacion estacion;
     private Tarjeta tarjeta;
     private double recargaValor;

    public Recarga() {
    }

    public Recarga(RecargaId id, Estacion estacion, Tarjeta tarjeta, double recargaValor) {
       this.id = id;
       this.estacion = estacion;
       this.tarjeta = tarjeta;
       this.recargaValor = recargaValor;
    }
   
    public RecargaId getId() {
        return this.id;
    }
    
    public void setId(RecargaId id) {
        this.id = id;
    }
    public Estacion getEstacion() {
        return this.estacion;
    }
    
    public void setEstacion(Estacion estacion) {
        this.estacion = estacion;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public double getRecargaValor() {
        return this.recargaValor;
    }
    
    public void setRecargaValor(double recargaValor) {
        this.recargaValor = recargaValor;
    }




}


