package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private String rutaId;
     private String rutaDescrip;
     private Set<Aborda> abordas = new HashSet<Aborda>(0);
     private Set<Transita> transitas = new HashSet<Transita>(0);
     private Set<Bus> buses = new HashSet<Bus>(0);

    public Ruta() {
    }

	
    public Ruta(String rutaId, String rutaDescrip) {
        this.rutaId = rutaId;
        this.rutaDescrip = rutaDescrip;
    }
    public Ruta(String rutaId, String rutaDescrip, Set<Aborda> abordas, Set<Transita> transitas, Set<Bus> buses) {
       this.rutaId = rutaId;
       this.rutaDescrip = rutaDescrip;
       this.abordas = abordas;
       this.transitas = transitas;
       this.buses = buses;
    }
   
    public String getRutaId() {
        return this.rutaId;
    }
    
    public void setRutaId(String rutaId) {
        this.rutaId = rutaId;
    }
    public String getRutaDescrip() {
        return this.rutaDescrip;
    }
    
    public void setRutaDescrip(String rutaDescrip) {
        this.rutaDescrip = rutaDescrip;
    }
    public Set<Aborda> getAbordas() {
        return this.abordas;
    }
    
    public void setAbordas(Set<Aborda> abordas) {
        this.abordas = abordas;
    }
    public Set<Transita> getTransitas() {
        return this.transitas;
    }
    
    public void setTransitas(Set<Transita> transitas) {
        this.transitas = transitas;
    }
    public Set<Bus> getBuses() {
        return this.buses;
    }
    
    public void setBuses(Set<Bus> buses) {
        this.buses = buses;
    }




}


