package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoBus generated by hbm2java
 */
public class TipoBus  implements java.io.Serializable {


     private int tpbusId;
     private String tpbusNombre;
     private Set<Bus> buses = new HashSet<Bus>(0);

    public TipoBus() {
    }

	
    public TipoBus(int tpbusId, String tpbusNombre) {
        this.tpbusId = tpbusId;
        this.tpbusNombre = tpbusNombre;
    }
    public TipoBus(int tpbusId, String tpbusNombre, Set<Bus> buses) {
       this.tpbusId = tpbusId;
       this.tpbusNombre = tpbusNombre;
       this.buses = buses;
    }
   
    public int getTpbusId() {
        return this.tpbusId;
    }
    
    public void setTpbusId(int tpbusId) {
        this.tpbusId = tpbusId;
    }
    public String getTpbusNombre() {
        return this.tpbusNombre;
    }
    
    public void setTpbusNombre(String tpbusNombre) {
        this.tpbusNombre = tpbusNombre;
    }
    public Set<Bus> getBuses() {
        return this.buses;
    }
    
    public void setBuses(Set<Bus> buses) {
        this.buses = buses;
    }




}


