package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * Aborda generated by hbm2java
 */
public class Aborda  implements java.io.Serializable {


     private AbordaId id;
     private Ruta ruta;
     private Tarjeta tarjeta;

    public Aborda() {
    }

    public Aborda(AbordaId id, Ruta ruta, Tarjeta tarjeta) {
       this.id = id;
       this.ruta = ruta;
       this.tarjeta = tarjeta;
    }
   
    public AbordaId getId() {
        return this.id;
    }
    
    public void setId(AbordaId id) {
        this.id = id;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }




}


