package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AbordaId generated by hbm2java
 */
public class AbordaId  implements java.io.Serializable {


     private int abordaTarjeta;
     private Date abordaFechaHora;

    public AbordaId() {
    }

    public AbordaId(int abordaTarjeta, Date abordaFechaHora) {
       this.abordaTarjeta = abordaTarjeta;
       this.abordaFechaHora = abordaFechaHora;
    }
   
    public int getAbordaTarjeta() {
        return this.abordaTarjeta;
    }
    
    public void setAbordaTarjeta(int abordaTarjeta) {
        this.abordaTarjeta = abordaTarjeta;
    }
    public Date getAbordaFechaHora() {
        return this.abordaFechaHora;
    }
    
    public void setAbordaFechaHora(Date abordaFechaHora) {
        this.abordaFechaHora = abordaFechaHora;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbordaId) ) return false;
		 AbordaId castOther = ( AbordaId ) other; 
         
		 return (this.getAbordaTarjeta()==castOther.getAbordaTarjeta())
 && ( (this.getAbordaFechaHora()==castOther.getAbordaFechaHora()) || ( this.getAbordaFechaHora()!=null && castOther.getAbordaFechaHora()!=null && this.getAbordaFechaHora().equals(castOther.getAbordaFechaHora()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAbordaTarjeta();
         result = 37 * result + ( getAbordaFechaHora() == null ? 0 : this.getAbordaFechaHora().hashCode() );
         return result;
   }   


}


