package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * AuxServCliente generated by hbm2java
 */
public class AuxServCliente  implements java.io.Serializable {


     private String auxServClienteEmpleadoId;
     private Empleado empleado;
     private Estacion estacion;

    public AuxServCliente() {
    }

    public AuxServCliente(Empleado empleado, Estacion estacion) {
       this.empleado = empleado;
       this.estacion = estacion;
    }
   
    public String getAuxServClienteEmpleadoId() {
        return this.auxServClienteEmpleadoId;
    }
    
    public void setAuxServClienteEmpleadoId(String auxServClienteEmpleadoId) {
        this.auxServClienteEmpleadoId = auxServClienteEmpleadoId;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Estacion getEstacion() {
        return this.estacion;
    }
    
    public void setEstacion(Estacion estacion) {
        this.estacion = estacion;
    }




}


