package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus  implements java.io.Serializable {


     private String busPlaca;
     private Ruta ruta;
     private TipoBus tipoBus;
     private Set<Conductor> conductors = new HashSet<Conductor>(0);

    public Bus() {
    }

	
    public Bus(String busPlaca, Ruta ruta, TipoBus tipoBus) {
        this.busPlaca = busPlaca;
        this.ruta = ruta;
        this.tipoBus = tipoBus;
    }
    public Bus(String busPlaca, Ruta ruta, TipoBus tipoBus, Set<Conductor> conductors) {
       this.busPlaca = busPlaca;
       this.ruta = ruta;
       this.tipoBus = tipoBus;
       this.conductors = conductors;
    }
   
    public String getBusPlaca() {
        return this.busPlaca;
    }
    
    public void setBusPlaca(String busPlaca) {
        this.busPlaca = busPlaca;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public TipoBus getTipoBus() {
        return this.tipoBus;
    }
    
    public void setTipoBus(TipoBus tipoBus) {
        this.tipoBus = tipoBus;
    }
    public Set<Conductor> getConductors() {
        return this.conductors;
    }
    
    public void setConductors(Set<Conductor> conductors) {
        this.conductors = conductors;
    }




}


