package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * DirOperativo generated by hbm2java
 */
public class DirOperativo  implements java.io.Serializable {


     private String dirOperativoEmpleadoId;
     private Empleado empleado;

    public DirOperativo() {
    }

    public DirOperativo(Empleado empleado) {
       this.empleado = empleado;
    }
   
    public String getDirOperativoEmpleadoId() {
        return this.dirOperativoEmpleadoId;
    }
    
    public void setDirOperativoEmpleadoId(String dirOperativoEmpleadoId) {
        this.dirOperativoEmpleadoId = dirOperativoEmpleadoId;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }




}


