package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String empleadoId;
     private String empleadoNombre;
     private String empleadoTelefono;
     private String empleadoSueldo;
     private int empleadoRol;
     private AuxServCliente auxServCliente;
     private Gerente gerente;
     private DirOperativo dirOperativo;
     private Conductor conductor;
     private Administrador administrador;

    public Empleado() {
    }

	
    public Empleado(String empleadoId, String empleadoNombre, String empleadoTelefono, String empleadoSueldo, int empleadoRol) {
        this.empleadoId = empleadoId;
        this.empleadoNombre = empleadoNombre;
        this.empleadoTelefono = empleadoTelefono;
        this.empleadoSueldo = empleadoSueldo;
        this.empleadoRol = empleadoRol;
    }
    public Empleado(String empleadoId, String empleadoNombre, String empleadoTelefono, String empleadoSueldo, int empleadoRol, AuxServCliente auxServCliente, Gerente gerente, DirOperativo dirOperativo, Conductor conductor, Administrador administrador) {
       this.empleadoId = empleadoId;
       this.empleadoNombre = empleadoNombre;
       this.empleadoTelefono = empleadoTelefono;
       this.empleadoSueldo = empleadoSueldo;
       this.empleadoRol = empleadoRol;
       this.auxServCliente = auxServCliente;
       this.gerente = gerente;
       this.dirOperativo = dirOperativo;
       this.conductor = conductor;
       this.administrador = administrador;
    }
   
    public String getEmpleadoId() {
        return this.empleadoId;
    }
    
    public void setEmpleadoId(String empleadoId) {
        this.empleadoId = empleadoId;
    }
    public String getEmpleadoNombre() {
        return this.empleadoNombre;
    }
    
    public void setEmpleadoNombre(String empleadoNombre) {
        this.empleadoNombre = empleadoNombre;
    }
    public String getEmpleadoTelefono() {
        return this.empleadoTelefono;
    }
    
    public void setEmpleadoTelefono(String empleadoTelefono) {
        this.empleadoTelefono = empleadoTelefono;
    }
    public String getEmpleadoSueldo() {
        return this.empleadoSueldo;
    }
    
    public void setEmpleadoSueldo(String empleadoSueldo) {
        this.empleadoSueldo = empleadoSueldo;
    }
    public int getEmpleadoRol() {
        return this.empleadoRol;
    }
    
    public void setEmpleadoRol(int empleadoRol) {
        this.empleadoRol = empleadoRol;
    }
    public AuxServCliente getAuxServCliente() {
        return this.auxServCliente;
    }
    
    public void setAuxServCliente(AuxServCliente auxServCliente) {
        this.auxServCliente = auxServCliente;
    }
    public Gerente getGerente() {
        return this.gerente;
    }
    
    public void setGerente(Gerente gerente) {
        this.gerente = gerente;
    }
    public DirOperativo getDirOperativo() {
        return this.dirOperativo;
    }
    
    public void setDirOperativo(DirOperativo dirOperativo) {
        this.dirOperativo = dirOperativo;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }




}


