package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion  implements java.io.Serializable {


     private int estacionId;
     private String estacionNombre;
     private String estacionUbicacion;
     private Administrador estacionAdministrador;
     private Set<Transita> transitasForTransitaSigEstacion = new HashSet<Transita>(0);
     private Set<Recarga> recargas = new HashSet<Recarga>(0);
     private Set<Transita> transitasForTransitaEstacion = new HashSet<Transita>(0);
     private Set<AuxServCliente> auxServClientes = new HashSet<AuxServCliente>(0);
     private Set<Pqrs> pqrses = new HashSet<Pqrs>(0);

    public Estacion() {
    }

	
    public Estacion(int estacionId, String estacionNombre, String estacionUbicacion, Administrador estacionAdministrador) {
        this.estacionId = estacionId;
        this.estacionNombre = estacionNombre;
        this.estacionUbicacion = estacionUbicacion;
        this.estacionAdministrador = estacionAdministrador;
    }
    public Estacion(int estacionId, String estacionNombre, String estacionUbicacion, Administrador estacionAdministrador, Set<Transita> transitasForTransitaSigEstacion, Set<Recarga> recargas, Set<Transita> transitasForTransitaEstacion, Set<AuxServCliente> auxServClientes, Set<Pqrs> pqrses) {
       this.estacionId = estacionId;
       this.estacionNombre = estacionNombre;
       this.estacionUbicacion = estacionUbicacion;
       this.estacionAdministrador = estacionAdministrador;
       this.transitasForTransitaSigEstacion = transitasForTransitaSigEstacion;
       this.recargas = recargas;
       this.transitasForTransitaEstacion = transitasForTransitaEstacion;
       this.auxServClientes = auxServClientes;
       this.pqrses = pqrses;
    }
   
    public int getEstacionId() {
        return this.estacionId;
    }
    
    public void setEstacionId(int estacionId) {
        this.estacionId = estacionId;
    }
    public String getEstacionNombre() {
        return this.estacionNombre;
    }
    
    public void setEstacionNombre(String estacionNombre) {
        this.estacionNombre = estacionNombre;
    }
    public String getEstacionUbicacion() {
        return this.estacionUbicacion;
    }
    
    public void setEstacionUbicacion(String estacionUbicacion) {
        this.estacionUbicacion = estacionUbicacion;
    }
    public Administrador getEstacionAdministrador() {
        return this.estacionAdministrador;
    }
    
    public void setEstacionAdministrador(Administrador estacionAdministrador) {
        this.estacionAdministrador = estacionAdministrador;
    }
    public Set<Transita> getTransitasForTransitaSigEstacion() {
        return this.transitasForTransitaSigEstacion;
    }
    
    public void setTransitasForTransitaSigEstacion(Set<Transita> transitasForTransitaSigEstacion) {
        this.transitasForTransitaSigEstacion = transitasForTransitaSigEstacion;
    }
    public Set<Recarga> getRecargas() {
        return this.recargas;
    }
    
    public void setRecargas(Set<Recarga> recargas) {
        this.recargas = recargas;
    }
    public Set<Transita> getTransitasForTransitaEstacion() {
        return this.transitasForTransitaEstacion;
    }
    
    public void setTransitasForTransitaEstacion(Set<Transita> transitasForTransitaEstacion) {
        this.transitasForTransitaEstacion = transitasForTransitaEstacion;
    }
    public Set<AuxServCliente> getAuxServClientes() {
        return this.auxServClientes;
    }
    
    public void setAuxServClientes(Set<AuxServCliente> auxServClientes) {
        this.auxServClientes = auxServClientes;
    }
    public Set<Pqrs> getPqrses() {
        return this.pqrses;
    }
    
    public void setPqrses(Set<Pqrs> pqrses) {
        this.pqrses = pqrses;
    }




}


