package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * Gerente generated by hbm2java
 */
public class Gerente  implements java.io.Serializable {


     private String gerenteEmpleadoId;
     private Empleado empleado;

    public Gerente() {
    }

    public Gerente(Empleado empleado) {
       this.empleado = empleado;
    }
   
    public String getGerenteEmpleadoId() {
        return this.gerenteEmpleadoId;
    }
    
    public void setGerenteEmpleadoId(String gerenteEmpleadoId) {
        this.gerenteEmpleadoId = gerenteEmpleadoId;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }




}


