package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * PqrsMedidaId generated by hbm2java
 */
public class PqrsMedidaId  implements java.io.Serializable {


     private int pqrsMedidaId;
     private int pqrsMedidaTicket;

    public PqrsMedidaId() {
    }

    public PqrsMedidaId(int pqrsMedidaId, int pqrsMedidaTicket) {
       this.pqrsMedidaId = pqrsMedidaId;
       this.pqrsMedidaTicket = pqrsMedidaTicket;
    }
   
    public int getPqrsMedidaId() {
        return this.pqrsMedidaId;
    }
    
    public void setPqrsMedidaId(int pqrsMedidaId) {
        this.pqrsMedidaId = pqrsMedidaId;
    }
    public int getPqrsMedidaTicket() {
        return this.pqrsMedidaTicket;
    }
    
    public void setPqrsMedidaTicket(int pqrsMedidaTicket) {
        this.pqrsMedidaTicket = pqrsMedidaTicket;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PqrsMedidaId) ) return false;
		 PqrsMedidaId castOther = ( PqrsMedidaId ) other; 
         
		 return (this.getPqrsMedidaId()==castOther.getPqrsMedidaId())
 && (this.getPqrsMedidaTicket()==castOther.getPqrsMedidaTicket());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPqrsMedidaId();
         result = 37 * result + this.getPqrsMedidaTicket();
         return result;
   }   


}


