package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RecargaId generated by hbm2java
 */
public class RecargaId  implements java.io.Serializable {


     private int recargaTarjeta;
     private Date recargaFechaHora;

    public RecargaId() {
    }

    public RecargaId(int recargaTarjeta, Date recargaFechaHora) {
       this.recargaTarjeta = recargaTarjeta;
       this.recargaFechaHora = recargaFechaHora;
    }
   
    public int getRecargaTarjeta() {
        return this.recargaTarjeta;
    }
    
    public void setRecargaTarjeta(int recargaTarjeta) {
        this.recargaTarjeta = recargaTarjeta;
    }
    public Date getRecargaFechaHora() {
        return this.recargaFechaHora;
    }
    
    public void setRecargaFechaHora(Date recargaFechaHora) {
        this.recargaFechaHora = recargaFechaHora;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecargaId) ) return false;
		 RecargaId castOther = ( RecargaId ) other; 
         
		 return (this.getRecargaTarjeta()==castOther.getRecargaTarjeta())
 && ( (this.getRecargaFechaHora()==castOther.getRecargaFechaHora()) || ( this.getRecargaFechaHora()!=null && castOther.getRecargaFechaHora()!=null && this.getRecargaFechaHora().equals(castOther.getRecargaFechaHora()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRecargaTarjeta();
         result = 37 * result + ( getRecargaFechaHora() == null ? 0 : this.getRecargaFechaHora().hashCode() );
         return result;
   }   


}


