package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private int tarjetaPin;
     private Usuario usuario;
     private String tarjetaSaldo;
     private boolean tarjetaEstado;
     private Set<Aborda> abordas = new HashSet<Aborda>(0);
     private Set<Recarga> recargas = new HashSet<Recarga>(0);

    public Tarjeta() {
    }

	
    public Tarjeta(int tarjetaPin, Usuario usuario, String tarjetaSaldo, boolean tarjetaEstado) {
        this.tarjetaPin = tarjetaPin;
        this.usuario = usuario;
        this.tarjetaSaldo = tarjetaSaldo;
        this.tarjetaEstado = tarjetaEstado;
    }
    public Tarjeta(int tarjetaPin, Usuario usuario, String tarjetaSaldo, boolean tarjetaEstado, Set<Aborda> abordas, Set<Recarga> recargas) {
       this.tarjetaPin = tarjetaPin;
       this.usuario = usuario;
       this.tarjetaSaldo = tarjetaSaldo;
       this.tarjetaEstado = tarjetaEstado;
       this.abordas = abordas;
       this.recargas = recargas;
    }
   
    public int getTarjetaPin() {
        return this.tarjetaPin;
    }
    
    public void setTarjetaPin(int tarjetaPin) {
        this.tarjetaPin = tarjetaPin;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTarjetaSaldo() {
        return this.tarjetaSaldo;
    }
    
    public void setTarjetaSaldo(String tarjetaSaldo) {
        this.tarjetaSaldo = tarjetaSaldo;
    }
    public boolean isTarjetaEstado() {
        return this.tarjetaEstado;
    }
    
    public void setTarjetaEstado(boolean tarjetaEstado) {
        this.tarjetaEstado = tarjetaEstado;
    }
    public Set<Aborda> getAbordas() {
        return this.abordas;
    }
    
    public void setAbordas(Set<Aborda> abordas) {
        this.abordas = abordas;
    }
    public Set<Recarga> getRecargas() {
        return this.recargas;
    }
    
    public void setRecargas(Set<Recarga> recargas) {
        this.recargas = recargas;
    }




}


