package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * TransitaId generated by hbm2java
 */
public class TransitaId  implements java.io.Serializable {


     private String transitaRuta;
     private int transitaEstacion;
     private int transitaSigEstacion;

    public TransitaId() {
    }

    public TransitaId(String transitaRuta, int transitaEstacion, int transitaSigEstacion) {
       this.transitaRuta = transitaRuta;
       this.transitaEstacion = transitaEstacion;
       this.transitaSigEstacion = transitaSigEstacion;
    }
   
    public String getTransitaRuta() {
        return this.transitaRuta;
    }
    
    public void setTransitaRuta(String transitaRuta) {
        this.transitaRuta = transitaRuta;
    }
    public int getTransitaEstacion() {
        return this.transitaEstacion;
    }
    
    public void setTransitaEstacion(int transitaEstacion) {
        this.transitaEstacion = transitaEstacion;
    }
    public int getTransitaSigEstacion() {
        return this.transitaSigEstacion;
    }
    
    public void setTransitaSigEstacion(int transitaSigEstacion) {
        this.transitaSigEstacion = transitaSigEstacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TransitaId) ) return false;
		 TransitaId castOther = ( TransitaId ) other; 
         
		 return ( (this.getTransitaRuta()==castOther.getTransitaRuta()) || ( this.getTransitaRuta()!=null && castOther.getTransitaRuta()!=null && this.getTransitaRuta().equals(castOther.getTransitaRuta()) ) )
 && (this.getTransitaEstacion()==castOther.getTransitaEstacion())
 && (this.getTransitaSigEstacion()==castOther.getTransitaSigEstacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransitaRuta() == null ? 0 : this.getTransitaRuta().hashCode() );
         result = 37 * result + this.getTransitaEstacion();
         result = 37 * result + this.getTransitaSigEstacion();
         return result;
   }   


}


