package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1



/**
 * Transita generated by hbm2java
 */
public class Transita  implements java.io.Serializable {


     private TransitaId id;
     private Estacion estacionByTransitaSigEstacion;
     private Estacion estacionByTransitaEstacion;
     private Ruta ruta;

    public Transita() {
    }

    public Transita(TransitaId id, Estacion estacionByTransitaSigEstacion, Estacion estacionByTransitaEstacion, Ruta ruta) {
       this.id = id;
       this.estacionByTransitaSigEstacion = estacionByTransitaSigEstacion;
       this.estacionByTransitaEstacion = estacionByTransitaEstacion;
       this.ruta = ruta;
    }
   
    public TransitaId getId() {
        return this.id;
    }
    
    public void setId(TransitaId id) {
        this.id = id;
    }
    public Estacion getEstacionByTransitaSigEstacion() {
        return this.estacionByTransitaSigEstacion;
    }
    
    public void setEstacionByTransitaSigEstacion(Estacion estacionByTransitaSigEstacion) {
        this.estacionByTransitaSigEstacion = estacionByTransitaSigEstacion;
    }
    public Estacion getEstacionByTransitaEstacion() {
        return this.estacionByTransitaEstacion;
    }
    
    public void setEstacionByTransitaEstacion(Estacion estacionByTransitaEstacion) {
        this.estacionByTransitaEstacion = estacionByTransitaEstacion;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }




}


