package Mapeo;
// Generated 17/12/2016 12:40:10 PM by Hibernate Tools 4.3.1


import java.lang.String;
import java.util.HashSet;
import java.util.Set;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private int turnoId;
     private String turnoDiaInicio;
     private String turnoDiaFin;
     private String turnoHoraInicio;
     private String turnoHoraFin;
     private Set<Conductor> conductors = new HashSet<Conductor>(0);

    public Turno() {
    }

	
    public Turno(int turnoId, String turnoDiaInicio, String turnoHoraInicio, String turnoHoraFin) {
        this.turnoId = turnoId;
        this.turnoDiaInicio = turnoDiaInicio;
        this.turnoHoraInicio = turnoHoraInicio;
        this.turnoHoraFin = turnoHoraFin;
    }
    public Turno(int turnoId, String turnoDiaInicio, String turnoDiaFin, String turnoHoraInicio, String turnoHoraFin, Set<Conductor> conductors) {
       this.turnoId = turnoId;
       this.turnoDiaInicio = turnoDiaInicio;
       this.turnoDiaFin = turnoDiaFin;
       this.turnoHoraInicio = turnoHoraInicio;
       this.turnoHoraFin = turnoHoraFin;
       this.conductors = conductors;
    }
   
    public int getTurnoId() {
        return this.turnoId;
    }
    
    public void setTurnoId(int turnoId) {
        this.turnoId = turnoId;
    }
    public String getTurnoDiaInicio() {
        return this.turnoDiaInicio;
    }
    
    public void setTurnoDiaInicio(String turnoDiaInicio) {
        this.turnoDiaInicio = turnoDiaInicio;
    }
    public String getTurnoDiaFin() {
        return this.turnoDiaFin;
    }
    
    public void setTurnoDiaFin(String turnoDiaFin) {
        this.turnoDiaFin = turnoDiaFin;
    }
    public String getTurnoHoraInicio() {
        return this.turnoHoraInicio;
    }
    
    public void setTurnoHoraInicio(String turnoHoraInicio) {
        this.turnoHoraInicio = turnoHoraInicio;
    }
    public String getTurnoHoraFin() {
        return this.turnoHoraFin;
    }
    
    public void setTurnoHoraFin(String turnoHoraFin) {
        this.turnoHoraFin = turnoHoraFin;
    }
    public Set<Conductor> getConductors() {
        return this.conductors;
    }
    
    public void setConductors(Set<Conductor> conductors) {
        this.conductors = conductors;
    }




}


